// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbo-_dIUwm2IDNFGMpfLFOeffUnu_jaew',
    appId: '1:84126507818:web:b4aebb11de4eb48618f453',
    messagingSenderId: '84126507818',
    projectId: 'chat-app-eae4d',
    authDomain: 'chat-app-eae4d.firebaseapp.com',
    storageBucket: 'chat-app-eae4d.appspot.com',
    measurementId: 'G-J6CCVVFTS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmigc6yUHVJvZJ-jMf5DhIYkr6FZVywP0',
    appId: '1:84126507818:android:a789cf3e4e53e42218f453',
    messagingSenderId: '84126507818',
    projectId: 'chat-app-eae4d',
    storageBucket: 'chat-app-eae4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7knXPKKewhXVj-QKygMKbyEEe6q8OfN8',
    appId: '1:84126507818:ios:2e661a74224e25ee18f453',
    messagingSenderId: '84126507818',
    projectId: 'chat-app-eae4d',
    storageBucket: 'chat-app-eae4d.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7knXPKKewhXVj-QKygMKbyEEe6q8OfN8',
    appId: '1:84126507818:ios:1922051633495e0518f453',
    messagingSenderId: '84126507818',
    projectId: 'chat-app-eae4d',
    storageBucket: 'chat-app-eae4d.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
